### ISSUE TITLE
KNN algorithm when using sigma and K as inputs

### ISSUE THREAD

**Issue by dkobak** [KlugerLab/FIt-SNE#15]
When input parameters `sigma` and `K` are provided and `theta>0` is used, then the code always uses VP trees, independent of what `knn_algo` is set to. Is this intended? I could fix it, or am I missing something here?

See https://github.com/KlugerLab/FIt-SNE/blob/master/src/tsne.cpp#L182. Even though the ANNOY version of `computeGaussianPerplexity()` function does support `sigma` as input.

By the way, this option is an interesting addition to the BH t-SNE codebase. I have also been experimenting with fixed sigmas to better understand the influence of the perplexity choice on t-SNE performance.

As an aside, I noticed that using small `K` and large `sigma` (something like `sigma=100` and `K=10`), which effectively yields almost binary affinity matrix, often yields quite good results, and similar to `perplexity=10`. This becomes something like a K-nearest-neighbours graph embedding algorithm...

**Comment by linqiaozhi** [comment]
To be honest, I added the sigma and K parameters for a fixed Gaussian kernel a while ago for a different project, but I found that adaptive kernel you get from using perplexity worked a lot better in the (admittedly few) cases I tried. Since then, I did not play with it much, so it is possible that later changes screwed it up.

So, yes, that is definitely a bug, and should be fixed.

It is interesting though that it works well when you do sigma=100 and K=10. I guess that can be thought of as an "adaptive kernel," in that for regions with few points, the affinities to far points are the same as the distances to very close points in dense regions.

**Comment by dkobak** [comment]
I started fixing it and realized the following.

In your current code, perplexity<0 always uses VP trees:
https://github.com/KlugerLab/FIt-SNE/blob/master/src/tsne.cpp#L184

But the VP tree function does not handle perplexity<0 case!
https://github.com/KlugerLab/FIt-SNE/blob/master/src/tsne.cpp#L1250 -- this is run even for perplexity<0 (I'm not sure what actually comes out of it then.)

Unlike the ANNOY function that does handle it:
https://github.com/KlugerLab/FIt-SNE/blob/master/src/tsne.cpp#L1085
but never gets called in this situation.

**Comment by dkobak** [comment]
And a question: in the Matlab/R wrappers, `search_k` is set to `3 * perplexity * n_trees` by default. However, if `perplexity==-1` then this clearly does not make sense (I was hunting down this bug for quite a while...). I think `3 * K * n_trees` should be used, can you confirm?

**Comment by dkobak** [comment]
I added K and sigma support to all three wrappers. And fixed the algorithm choice when using sigma and K. Will pull request this now.

**Comment by linqiaozhi** [comment]
Pull request was merged, thanks so much!!
