### ISSUE TITLE
Changing output despite using the same initialization

### ISSUE THREAD

**Issue by dkobak** [KlugerLab/FIt-SNE#46]
I noticed that in some cases I get slightly different output if I rerun the exact same code, even though I provide the same initialization. I am wondering where the additional randomness can come from. I am thinking maybe the randomness comes from Annoy. If so, I think Annoy allows to set the seed.

Should we pass the `rand_seed` parameter (that we have anyway) to Annoy?

**Comment by linqiaozhi** [comment]
Yes, you are right. It has to be due to Annoy, and we should pass the same seed to it. Another great catch.

**Comment by dkobak** [comment]
I can PR this after the currently pending PR is merged.

**Comment by dkobak** [comment]
Hmm. I implemented it, but it turns out that the problem is more involved.

Actually running `fast_tsne` always produces the same result in my example (whether the same Annoy seed is used or not), so what I wrote above was incorrect. I have a pipeline that takes some data X, runs PCA to get it down to 50 dimensions, then passes this to `fast_tsne`. If I run the PCA part twice, I get X1 and X2 which appear to be similar to machine precision: dimensions 25k x 50, values from 0 to ~100, `np.max((X1-X2)**2)` is e-23. However, if I run

```
Z1 = fast_tsne(X1, perplexity = 30, initialization = myInit, max_iter=500, seed=42)
Z2 = fast_tsne(X2, perplexity = 30, initialization = myInit, max_iter=500, seed=42)
```

I get slightly different results! The difference is noticeable because some of the clusters sometime end up in different places. As a sanity check,

```
Z3 = fast_tsne(X1, perplexity = 30, initialization = myInit, max_iter=500, seed=42)
Z4 = fast_tsne(X1, perplexity = 30, initialization = myInit, max_iter=500, seed=42)
```

(when I both times use `X1`) yield exactly the same result.

This happens only if I use `scipy.sparse.linalg.svds`. If I use `numpy.linalg.svd`, then `np.max((X1-X2)**2)` is actually 0, not e-23, and the t-SNE output is also the same. I was using `svds` because it's faster.

I guess there are two lessons here:
(1) `svds` is less then precise than `svd`, even though the default tolerance in `svds` is zero. The former uses ARPACK, the latter LAPACK...
(2) t-SNE can be sensitive to microscopic difference in X. I still suspect that it's because of Annoy, but this isn't something we can fix via random seed.

**Comment by dkobak** [comment]
Some discussion about seeding `svds` is here https://github.com/scipy/scipy/issues/9023.

Anyway, given that seeding Annoy does not seem to produce any difference (using the data I tried), should I still PR this or let it be as is?

**Comment by linqiaozhi** [comment]
It really is interesting that such tiny differences can qualitatively effect the t-SNE.  I guess it's because they are amplified over the course of the many iterations. That being said, machine precision is so small...I am quite surprised by that.

Anyways, even though it does not seem to materially affect the results, please go ahead and PR it. I think that if people set a seed they expect it to be set everywhere...and there are likely some cases where it might make a difference.  

As an aside, is it possible that seeding Annoy does not produce any difference because when we [set](https://github.com/KlugerLab/FIt-SNE/blob/master/src/tsne.cpp#L109-L117) 
the seed using srand() it maybe sets it "program-wide?" That is, perhaps we are actually setting the seed for Annoy as well when we set it using srand()? I'm not sure if the random number generators in different parts of the code are independent...

**Comment by dkobak** [comment]
> That is, perhaps we are actually setting the seed for Annoy as well when we set it using srand()?

You are right, that's possible. No idea. Anyway, I think it's better to explicitly set the seed given that Annoy's API allows that.

**Comment by dkobak** [comment]
Closing now that #47 is merged.
