### ISSUE TITLE
How to properly pass the perplexity_list parameter?

### ISSUE THREAD

**Issue by davisidarta** [KlugerLab/FIt-SNE#77]
Hi there! Thank you for this awesome implementation of tSNE! 

I would like to know how to use the perplexity_list parameter, since there is no further documentation on it.  Is it possible to get multiple perplexities for the same tSNE plot? If so, does the order of the values in the list represent anything to the algorithm?

**Comment by dkobak** [comment]
Hi, thanks for the interest. I will reply because I implemented this functionality.

At least the Python wrapper provides the following documentation:

```    
perplexity_list: list
        A list of perplexities to used as a perplexity combination. Input affinities are computed with each
        perplexity on the list and then averaged. Default is None.
```

The order of the values in the list does not matter.

You can find a usage example in the example Python notebook: https://github.com/KlugerLab/FIt-SNE/blob/master/examples/test.ipynb

See this preprint for the description of what exactly "perplexity combination" means, and further references: https://www.biorxiv.org/content/10.1101/453449v2

I'm closing this issue; feel free to reopen if this does not answer your question.
