### ISSUE TITLE
Do I need to install FFTW for windows? If I am using Python

### ISSUE THREAD

**Issue by Dadatata-JZ** [KlugerLab/FIt-SNE#79]
Hi there, 
I followed this, and tried to run jupyter notebook example. But it was working and returned the error of filenotfound

![image](https://user-images.githubusercontent.com/31292151/67045322-0bafb480-f0fc-11e9-89f9-f7f147a88c4f.png)

**Comment by Liangti-Dai** [comment]
Exactly the same with me! Have you solved it?

**Comment by pavlin-policar** [comment]
Just to clarify on this a little bit, openTSNE relies on the FFT as well, the difference is that FFTW is an optional dependency. If it isn't available, it will use numpy's FFT implementation, which, according to my benchmarks, isn't really much slower than FFTW. This is if you build from source, which you normally don't. You normally install using pip, and openTSNE has prebuilt wheels which means everything *just works* right away. That was kind of the goal of openTSNE. However, openTSNE is a bit slower than FIt-SNE, so that may be something to consider.

**Comment by linqiaozhi** [comment]
Some updates had broken FIt-SNE's Windows support, but that is now fixed in FIt-SNE v1.2.1. And it should not require you to install FFTW, nor should you need to compile anything. You just need to extract the zip file into the bin folder...the DLL for FFTW is in that zip file.
