### ISSUE TITLE
FIt-SNE with MATLAB wrapper significanlty slower than built-in implementation...????

### ISSUE THREAD

**Issue by sg-s** [KlugerLab/FIt-SNE#86]
Hi, 

I'm playing around the [fast_tsne](https://github.com/KlugerLab/FIt-SNE/blob/master/fast_tsne.m) wrapper, and trying to embed a N=5000 test dataset

```matlab
X = [randn(5e3,1) randn(5e3,1)];
X(1:3:end,1) = X(1:3:end,1)+10;
X(2:3:end,2) = X(2:3:end,2)+10;
 plot(X(:,1),X(:,2),'k.')
```

<img width="504" alt="Screen Shot 2020-01-06 at 2 01 03 PM" src="https://user-images.githubusercontent.com/6005346/71841260-fdcf5700-308c-11ea-83e5-c65a3f362abf.png">

I can embed it using `fast_tsne` as follows:

```
opts.nthreads = 8;
R = fast_tsne(X,opts);
Elapsed time is 39.793197 seconds.
```

This is considerably slower than MATLAB's built-in (which uses bhtsne). # of iterations is 1000 in both.

```
tic; R = tsne(X); toc
Elapsed time is 26.548633 seconds.
```

What I did notice is that the fast_tsne binary never used more than a single core. Is this expected behaviour? Am I doing something wrong? I don't understand why it's slower than expected.

**Comment by linqiaozhi** [comment]
FIt-SNE is not intended to be used with small number of points, because there is some overhead with the FFTs (although, notably, it's not by any means prohibitively slow!). After about 10,000 points you should see the speed-up over BH, and it is increasingly dramatic as you increase the number of points. 

You'll also only really see the multi-threading if you increase the number of points.

**Comment by dkobak** [comment]
FIt-SNE does have BH in it though, so you can try `fast_tsne` with BH method to see if it gets faster.

**Comment by sg-s** [comment]
Thanks, I feel like I must have missed something. I re-ran these tests with N=20,000, and it's actually **faster** than for N=5000. 

```
Elapsed time is 35.205586 seconds.
```

And I did see the multi-threading kick in here. Thanks again! Closing
